name: Team WALK
author: "Edward Nusinovich"
description: Gemstone
baseurl: 'https://ednusi.github.io/team-walk/'
[//]: # (baseurltemporary: 'https://ednusi.github.io/team-walk/')
port: 4000
gems: [jekyll-paginate]
paginate: 10

