name: Team WALK
author: "Edward Nusinovich"
description: Gemstone
baseurl: 'http://gemswalk.com'
[//]: # (baseurltemporary: 'https://ednusi.github.io/team-walk/')
port: 4000
gems: [jekyll-paginate]
paginate: 10
excerpt_separator: <!--more-->

